
services:
  frontend:
    image: snits/freeflix-react:${FREEFLIX_REACT_VERSION:-latest} # production build
    build: !reset null
    develop: !reset null
    stdin_open: false
    tty: false
    environment:
      - NODE_ENV=production

  backend:
    image: snits/freeflix-django:${FREEFLIX_DJANGO_VERSION:-latest}
    build: !reset null
    command: gunicorn freeflix.wsgi:application -b 0.0.0.0:8000

  node_backend:
    image: snits/freeflix-node-server:${FREEFLIX_NODE_VERSION:-latest}
    build: !reset null
    command: pm2-runtime start index.js --name node-media-server

  web_server:
    volumes:
      - ./nginx-server/config.conf:/etc/nginx/conf.d/default.conf