services:
  frontend:
    build:
      context: ./freeflix-react
      target: build
    env_file:
      - ./freeflix-react/.env.development
    develop:
      watch:
        - action: sync
          path: ./freeflix-react
          target: /app
          initial_sync: true
          ignore:
            - node_modules/
        - action: rebuild
          path: ./freeflix-react/package.json
    stdin_open: true
    tty: true
    command: ["npm", "start"]
  
  backend:
    develop:
      watch:
        - action: sync
          path: .
          initial_sync: true
          target: /app
    command: python manage.py runserver 0.0.0.0:8000

  node_backend:
    environment:
      - ENV_MODE=development
    develop:
      watch:
        - action: sync
          path: ./node-media-server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./node-media-server/package.json
    command: node index.js

  web-server:
    volumes:
      - ./nginx-server/config.dev.conf:/etc/nginx/conf.d/default.conf