server {
    listen 80;

    # React app production
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    include /etc/nginx/includes/app-common.conf;
}
