# Generated by Django 3.1 on 2020-08-28 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import flix.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('tmdb_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('date_release', models.DateField()),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster_path', models.CharField(max_length=256)),
                ('genres', models.ManyToManyField(to='flix.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('season_number', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='flix.series')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('date_release', models.DateField()),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster_path', models.CharField(max_length=256)),
                ('video', models.FileField(max_length=256, upload_to="")),
                ('genres', models.ManyToManyField(to='flix.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('video', models.FileField(max_length=256, upload_to="")),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='flix.season')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
