# Generated by Django 4.2.23 on 2025-06-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='video',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
