# Generated by Django 4.2.23 on 2025-08-17 10:32

from django.db import migrations, models
import flix.models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0002_remove_episode_video_remove_movie_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle',
            field=models.FileField(blank=True, null=True, upload_to=flix.models.subtitle_by_vid_path),
        ),
    ]
