# Generated by Django 4.2.23 on 2025-08-20 14:33

from django.db import migrations, models
import django.db.models.deletion
import flix.models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0003_movie_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subtitle', models.FileField(blank=True, null=True, upload_to=flix.models.subtitle_by_vid_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='subtitle',
        ),
        migrations.CreateModel(
            name='MovieSubtitle',
            fields=[
                ('subtitlebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flix.subtitlebase')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='flix.movie')),
            ],
            bases=('flix.subtitlebase',),
        ),
        migrations.CreateModel(
            name='EpisodeSubtitle',
            fields=[
                ('subtitlebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flix.subtitlebase')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='flix.episode')),
            ],
            bases=('flix.subtitlebase',),
        ),
    ]
