# Generated by Django 4.2.23 on 2025-08-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0004_subtitlebase_remove_movie_subtitle_moviesubtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitlebase',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
