# Generated by Django 4.2.23 on 2025-08-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0005_alter_subtitlebase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitlebase',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
