# Generated by Django 4.2.23 on 2025-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0006_alter_subtitlebase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlebase',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
