# Generated by Django 4.2.23 on 2025-08-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0007_subtitlebase_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitlebase',
            name='srclng',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
