# Generated by Django 4.2.23 on 2026-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0008_subtitlebase_srclng'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='extension',
            field=models.CharField(default='mp4', max_length=8),
        ),
        migrations.AddField(
            model_name='movie',
            name='extension',
            field=models.CharField(default='mp4', max_length=8),
        ),
    ]
